eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost

spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: lb://SERVICE-CLIENT
          predicates:
            - Path=/clients/**

